apiVersion: apps/v1
kind: Deployment
metadata:
  name: citysim-deployment
  labels:
    app: citysim
spec:
  replicas: 1
  selector:
    matchLabels:
      app: citysim
  template:
    metadata:
      labels:
        app: citysim
    spec:
      containers:
      - name: citysim
        image: tomabecea/citysim
        ports:
        - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: citysim
spec:
  selector:
    app: citysim
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000