version: '3'

services:
  graphhopper:
    build: ./graphhopper
    ports:
      - "8989:8989"  
  citysim:
    build: ./city/citysim
  cityactor:
    build: ./city/cityactor
    depends_on: 
      - "graphhopper"
